-- 生成 2026-01-01 00:00:00 至 2026-01-18 23:59:30，每30秒一条（MySQL 5.7 兼容）
-- sleep_status 覆盖 WAKE/DEEP/LIGHT/REM，并按完整睡眠周期循环
INSERT INTO health_data (user_id, heart_rate, breathing_rate, sleep_status, motion_index, upload_time)
SELECT
  'user123' AS user_id,
  CASE sleep_status
    WHEN 'DEEP' THEN FLOOR(50 + RAND() * 6)
    WHEN 'LIGHT' THEN FLOOR(56 + RAND() * 8)
    WHEN 'REM' THEN FLOOR(60 + RAND() * 10)
    ELSE FLOOR(70 + RAND() * 15)
  END AS heart_rate,
  CASE sleep_status
    WHEN 'DEEP' THEN FLOOR(10 + RAND() * 3)
    WHEN 'LIGHT' THEN FLOOR(12 + RAND() * 3)
    WHEN 'REM' THEN FLOOR(13 + RAND() * 4)
    ELSE FLOOR(15 + RAND() * 5)
  END AS breathing_rate,
  sleep_status,
  CASE sleep_status
    WHEN 'DEEP' THEN ROUND(5 + RAND() * 5, 2)
    WHEN 'LIGHT' THEN ROUND(10 + RAND() * 10, 2)
    WHEN 'REM' THEN ROUND(15 + RAND() * 15, 2)
    ELSE ROUND(30 + RAND() * 30, 2)
  END AS motion_index,
  upload_time
FROM (
  SELECT
    TIMESTAMP('2026-01-01 00:00:00') + INTERVAL (n * 30) SECOND AS upload_time,
    CASE
      WHEN (n % 180) < 50 THEN 'LIGHT'
      WHEN (n % 180) < 110 THEN 'DEEP'
      WHEN (n % 180) < 150 THEN 'REM'
      ELSE 'WAKE'
    END AS sleep_status
  FROM (
    SELECT (d4.i * 10000 + d3.i * 1000 + d2.i * 100 + d1.i * 10 + d0.i) AS n
    FROM (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d0
    CROSS JOIN
        (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d1
    CROSS JOIN
        (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d2
    CROSS JOIN
        (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d3
    CROSS JOIN
        (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d4
  ) nums
  WHERE n < (18 * 24 * 60 * 60 / 30)
) s;
